---
- name: "Download Consul"
  get_url:
    url: "{{ download_url }}"
    dest: "/tmp/{{ filename }}"
  notify: "restart consul service"

- name: "Unpacking binary"
  unarchive:
    src: "/tmp/{{ filename }}"
    dest: "/usr/bin"
    remote_src: True

- name: "Creating {{ consul_user }} group"
  group:
    name: "{{ consul_group }}"
    state: present

- name: "Creating {{ consul_user }} user"
  user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    state: present

- name: "Creating config dir"
  file:
    state: directory
    path: "/etc/consul.d"
    owner: "root"
    group: "root"

- name: "Creating data dir"
  file:
    state: directory
    path: "{{ data_dir }}"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"

- name: "Setting systemd service"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: "templates/consul.service.j2",
        dest: "/etc/systemd/system/consul.service"
      }
    - {
        src: "templates/agent.json",
        dest: "/etc/consul.d/agent.json"
      }

- name: "restart consul service"
  systemd:
    name: consul
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: "consul started.. " 
  wait_for:
    host: "127.0.0.1"
    port: "8500"
    delay: "3"


