- debug:
    var: ansible_service_mgr

- name: systemd unit
  template:
    src: vault-server.service.j2
    dest: /lib/systemd/system/vault.service
    owner: root
    group: root
    mode: "0644"
  when:
    - ansible_service_mgr == "systemd"
  register: vault_service_task_systemd

- name: Start vault server
  service:
    name: vault-server.service
    state: restarted
  when: ansible_service_mgr == "systemd" and (vault_log_task|changed or vault_service_task_systemd|changed)

