---

consul_version: "0.9.2"
filename: "consul_{{ consul_version }}_linux_amd64.zip"
download_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/{{ filename }}"
consul_user: "consul"
consul_port: "8500"
consul_group: "consul"
executable_location: "/usr/bin/consul"
datacenter: "default"
data_dir: "/var/lib/consul"
is_server: true
ui: true
client_addr: "0.0.0.0"
bind_addr: "127.0.0.1"
cluster:
  servers: [ "{{ bind_addr }}" ]
  clients: []

# defaults file for vault
vault_version: 0.9.0
vault_dir: /opt/vault
vault_user: vault
vault_user_password: $6$J9/cJI/s$a0bvktGj1hO1WMG.LDgLlfOFM3.dBSHBJA9d7euRiOvw4TUGWF7Y2SgjqcET4OCjeOupVR9XFM9EqWYIPdFDG.
vault_server: True
vault_server_mode: server
vault_server_log_dir: /var/log/vault
vault_server_log_level: info
vault_ttl: 2557920h
vault_server_config_path: /etc/vault
vault_port: "8200"
vault_address: "{{ inventory_hostname }}"
vault_url: "http://{{ inventory_hostname }}:{{vault_port}}"
environment:
    VAULT_ADDR: "{{vault_url}}"
vault_init_logs: "{{vault_dir}}/vault_init.log"
